name: Unit tests
run-name: ${{ github.actor }} running unit tests
on: [push]
jobs:
  run-defined-frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.19.0"
      - run: npm ci
      - run: npm run test
